ENVIRONMENT: local

ZOOTOPIA_API_KEY: key

OPENAI_API_KEY: key
ANTHROPIC_API_KEY: key
GROQ_API_KEY: key
GEMINI_API_KEY: key

TELEGRAM_BOT_TOKEN: key

BIRD_API_URL: https://api.bird.com
BIRD_API_KEY: key
BIRD_ORGANIZATION_ID: key
BIRD_WORKSPACE_ID: key
BIRD_DEV_CHANNEL_ID: key
BIRD_SIGNING_KEY: key

SUPABASE_URL: url
SUPABASE_KEY: key

GOOGLE_API_KEY: key
GOOGLE_CLIENT_ID: key
GOOGLE_CLIENT_SECRET: key

REDIS_URL: url
FLOWER_UNAUTHENTICATED_API: bool

FILTER_LLM: "groq/llama-3.1-70b-versatile"
SKIP_LLM: "groq/llama-3.1-70b-versatile"
ACTION_MANAGER_LLM_PROVIDER: "ANTHROPIC_API_KEY"
ACTION_MANAGER_LLM: "claude-3-5-sonnet-20240620"
INTENT_MANAGER_LLM: "claude-3-5-sonnet-20240620"
MEMORY_MANAGER_LLM: "claude-3-5-sonnet-20240620"
VISION_MANAGER_LLM_PROVIDER: "OPENAI_API_KEY"
VISION_MANAGER_LLM: "gpt-4o-mini"

STRIPE_SECRET_KEY: key
STRIPE_WEBHOOK_SECRET: key
STRIPE_PRODUCT_PRICE_ID: key

PHONE_OTP_CHANNEL_ID: key
FRONTEND_URL: http://localhost:3000/

MEMORY_GENERAL_LLM: gemini/gemini-1.5-flash
MEMORY_GENERAL_LLM_PROVIDER: GEMINI_API_KEY

MEMORY_VECTOR_STORE_PROVIDER: qdrant
MEMORY_QDRANT_CONFIG:
  url: url
  api_key: key
  collection_name: testing # or 'prod' for production
  embedding_model_dims: 1536

MEMORY_LLM_PROVIDER: litellm
MEMORY_LITELLM_CONFIG:
  model: gemini/gemini-pro
  temperature: 0.2
  max_tokens: 1000
  api_key: str

MEMORY_EMBEDDINGS_PROVIDER: openai
MEMORY_EMBEDDINGS_CONFIG:
  model: text-embedding-3-small
  embedding_dims: 1536
  api_key: str

ENABLE_RESPONSE_DELAY: true

TIME_API:
  default_timezone: "America/Chicago"

AWS_S3_CONFIG:
  access_key: key
  secret_access_key: key
  bucket: bucket
