import json
from datetime import date, datetime
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field, field_validator

from mini.utils.utils import generate_uuid, utc_now


# TODO: MOVE ALL THESE TO RESPECTIVE FOLDERS IN DATABASE
class Tables(str, Enum):
    """Tables and columns available in the database."""

    AGENTS = "agents"
    AGENTS__id = "id"
    AGENTS__name = "name"
    AGENTS__description = "description"
    AGENTS__first_message = "first_message"
    AGENTS_example_conversation = "example_conversation"
    AGENTS__bird_channel_id = "bird_channel_id"
    AGENTS__default_proactivity = "default_proactivity"
    AGENTS__free_msg_limit = "free_msg_limit"
    AGENTS__subscribe_msg = "subscribe_msg"
    AGENTS__allow_roleplay = "allow_roleplay"
    AGENTS__image_url = "image_url"
    AGENTS__prompt_role = "prompt_role"
    AGENTS__prompt_rules = "prompt_rules"
    AGENTS__prompt_moods = "prompt_moods"

    CHANNELS = "channels"
    CHANNELS__id = "id"
    CHANNELS__created_at = "created_at"
    CHANNELS__phone_number = "phone_number"
    CHANNELS__agent_id = "agent_id"
    CHANNELS__note = "note"
    CHANNELS__name = "name"

    USERS = "users"
    USERS__id = "id"
    USERS__created_at = "created_at"
    USERS__phone_number = "phone_number"
    USERS__telegram_uid = "telegram_uid"
    USERS__birthday = "birthday"
    USERS__customer_id = "customer_id"
    USERS__is_subscribed = "is_subscribed"
    USERS__litellm_cost = "litellm_cost"

    ROOMS = "rooms"
    ROOMS__id = "id"
    ROOMS__created_at = "created_at"
    ROOMS__user_id = "user_id"
    ROOMS__agent_id = "agent_id"
    ROOMS__agent_proactivity = "agent_proactivity"
    ROOMS__subscribe_msg_sent = "subscribe_msg_sent"
    ROOMS__disabled_by_admin = "disabled_by_admin"
    ROOMS__last_msg_sent_at = "last_msg_sent_at"
    ROOMS__agent_last_msg_sent_at = "agent_last_msg_sent_at"
    ROOMS__scheduled_send_id = "scheduled_send_id"

    MESSAGES = "messages"
    MESSAGES__id = "id"
    MESSAGES__sender_id = "sender_id"
    MESSAGES__room_id = "room_id"
    MESSAGES__created_at = "created_at"
    MESSAGES__content = "content"
    MESSAGES__type = "type"
    MESSAGES__sent_by_admin = "sent_by_admin"
    MESSAGES__log = "log"

    SUBSCRIPTIONS = "subscriptions"
    SUBSCRIPTIONS__id = "id"
    SUBSCRIPTIONS__user_id = "user_id"
    SUBSCRIPTIONS__status = "status"

    SCHEDULE = "schedule"
    SCHEDULE__id = "id"
    SCHEDULE__room_id = "room_id"
    SCHEDULE__message_id = "message_id"
    SCHEDULE__created_at = "created_at"
    SCHEDULE__scheduled_for = "scheduled_for"
    SCHEDULE__type = "type"  # respond, remind, revive
    SCHEDULE__info = "info"
    SCHEDULE__complete = "complete"

    IGACCOUNTS = "ig_accounts"
    IGACCOUNTS__id = "id"
    IGACCOUNTS__agent_id = "agent_id"
    IGACCOUNTS__account_id = "account_id"
    IGACCOUNTS__access_token = "access_token"
    IGACCOUNTS__access_token_expiration = "access_token_expiration"
    IGACCOUNTS__handle = "handle"

    def __str__(self) -> str:
        return self.value


class Agent(BaseModel):
    __tablename__ = Tables.AGENTS

    id: str = Field(default_factory=generate_uuid)
    name: str
    description: str
    first_message: str
    bird_channel_id: str
    free_msg_limit: int
    subscribe_msg: str
    default_proactivity: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Proactivity scale from 0 (not proactive) to 1 (very proactive)",
    )
    allow_roleplay: bool
    image_url: Optional[str]
    prompt_role: str
    prompt_rules: List[str]
    prompt_moods: List[str]


class Channel(BaseModel):
    id: str = Field(default_factory=generate_uuid)
    created_at: datetime = Field(default_factory=utc_now)
    phone_number: str
    agent_id: Optional[str]
    note: Optional[str]
    name: str


class User(BaseModel):
    id: str = Field(description="UUID generated by Supabase Auth")
    phone_number: str
    created_at: datetime = Field(default_factory=utc_now)
    birthday: Optional[str] = Field(default=None)
    telegram_uid: Optional[str] = Field(default=None)
    customer_id: Optional[str] = Field(default=None)
    is_subscribed: bool = Field(default=False)
    litellm_cost: float = Field(default=0.0)


class Room(BaseModel):
    id: str = Field(default_factory=generate_uuid)
    created_at: datetime = Field(default_factory=utc_now)
    user_id: str
    agent_id: str
    subscribe_msg_sent: bool = Field(default=False)
    agent_proactivity: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Agent proactivity for a particular room (0 if a user has texted STOP)",
    )
    disabled_by_admin: bool = Field(default=False)
    last_msg_sent_at: datetime = Field(
        default_factory=utc_now,
        description="Time of last message sent by either agent or user",
    )
    agent_last_msg_sent_at: datetime = Field(
        default_factory=utc_now,
        description="Time of last message sent by agent",
    )
    scheduled_send_id: Optional[str] = Field(default=None)


class Message(BaseModel):
    id: str = Field(default_factory=generate_uuid)
    sender_id: str
    room_id: str
    created_at: datetime = Field(default_factory=utc_now)
    content: str = Field(default=None)
    sent_by_admin: bool = Field(default=False)
    log: Optional[Union[List[Dict[str, Any]], str]] = Field(
        default=None, description="JSONB field for agent logs"
    )

    @field_validator("log", mode="before")
    def parse_log(cls, value):
        if isinstance(value, str):
            try:
                return json.loads(value)
            except json.JSONDecodeError:
                return value  # Leave it as string if it can't be parsed
        return value


class Subscription(BaseModel):
    id: str
    user_id: str
    status: str


class Schedule(BaseModel):
    id: str = Field(default_factory=generate_uuid)
    room_id: str
    message_id: Optional[str]
    created_at: datetime = Field(default_factory=utc_now)
    scheduled_for: str
    type: Literal["respond", "remind", "revive"] = Field(default="respond")
    task: Optional[str] = Field(default=None)
    complete: bool = Field(default=False)


class IGAccounts(BaseModel):
    id: str
    agent_id: str
    account_id: str
    access_token: str
    access_token_expiration: date
    handle: str


TableModel = Union[
    User, Agent, Channel, Room, Message, Schedule, Subscription, IGAccounts
]
TABLE_MODEL_MAP = {
    Tables.USERS: User,
    Tables.AGENTS: Agent,
    Tables.CHANNELS: Channel,
    Tables.ROOMS: Room,
    Tables.MESSAGES: Message,
    Tables.SCHEDULE: Schedule,
    Tables.SUBSCRIPTIONS: Subscription,
    Tables.IGACCOUNTS: IGAccounts,
}
