###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

file_map = {
    
    "clients.baml": "client<llm> GPT4o {\n  provider openai\n  options {\n    model \"gpt-4o\"\n    api_key env.OPENAI_API_KEY\n  }\n}\n\nclient<llm> Claude {\n  provider anthropic\n  options {\n    model \"claude-3-5-sonnet-20240620\"\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n\nclient<llm> FastAnthropic {\n  provider anthropic\n  options {\n    model \"claude-3-haiku-20240307\"\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n\nclient<llm> FastOpenAI {\n  provider openai\n  options {\n    model \"gpt-4o-mini\"\n    api_key env.OPENAI_API_KEY\n  }\n}\n\nclient<llm> Fast {\n  provider round-robin\n  options {\n    strategy [FastAnthropic, FastOpenAI]\n  }\n}\n\nclient<llm> Openai {\n  provider fallback\n  options {\n    strategy [GPT4, FastOpenAI]\n  }\n}",
    "generators.baml": "\n// This helps use auto generate libraries you can use in the language of\n// your choice. You can have multiple generators if you use multiple languages.\n// Just ensure that the output_dir is different for each generator.\ngenerator target {\n    // Valid values: \"python/pydantic\", \"typescript\", \"ruby/sorbet\"\n    output_type \"python/pydantic\"\n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../\"\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\n    // The BAML VSCode extension version should also match this version.\n    version \"0.54.0\"\n    // Valid values: \"sync\", \"async\"\n    // This controls what `b.FunctionName()` will be (sync or async).\n    // Regardless of this setting, you can always explicitly call either of the following:\n    // - b.sync.FunctionName()\n    // - b.async_.FunctionName() (note the underscore to avoid a keyword conflict)\n    default_client_mode sync\n}",
    "resume.baml": "enum Category {\n  UserPreferenceUpdate @description(\"Update user's preferences based on feedback about Sam\")\n  PersonalityAdjustment @description(\"Adjust Sam's personality traits or behavior\")\n  ScheduleUpdate @description(\"Update or create events in the user's schedule\")\n  RelationshipMilestone @description(\"Mark important events or milestones in the relationship\")\n  EmotionalResponse @description(\"Trigger an appropriate emotional response from Sam\")\n  MemoryStorage @description(\"Store important information shared by the user\")\n  ConversationTopic @description(\"Identify and log conversation topics for future reference\")\n  UserMoodTracking @description(\"Track and respond to changes in the user's mood\")\n  InteractionFrequencyAdjustment @alias(\"frequency-adjust\") @description(\"Adjust how often Sam initiates conversations\")\n  ContentSuggestion @description(\"Generate content suggestions based on user interests\")\n}\n\nfunction ClassifyMessage(input: string) -> Category {\n  client \"openai/gpt-4o\"\n  prompt #\"\n    {{ ctx.output_format }}\n    \n    {{ _.role('user') }}\n    {{ input }}\n    \n    {{ _.role('assistant') }}\n    Response:\n  \"#\n}",
}

def get_baml_files():
    return file_map