from enum import Enum
from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional, Type, Union, Any, Literal
from pydantic import BaseModel, Field, field_validator
import json
import uuid
from uuid import UUID


class Tables(str, Enum):
    """Tables available in the database."""

    AGENTS = "agents"
    AGENTS__id = "id"
    AGENTS__first_message = "first_message"
    AGENTS__bird_channel_id = "bird_channel_id"
    AGENTS__telegram_chat_id = "telegram_chat_id"
    AGENTS__default_proactivity = "default_proactivity"
    AGENTS__subscribe_enabled = "subscribe_enabled"
    AGENTS__free_msg_limit = "free_msg_limit"
    AGENTS__subscribe_msg = "subscribe_msg"
    AGENTS__subscribe_url = "subscribe_url"

    USERS = "users"
    USERS__id = "id"
    USERS__created_at = "created_at"
    USERS__phone_number = "phone_number"
    USERS__telegram_uid = "telegram_uid"
    USERS__birthday = "birthday"
    USERS__customer_id = "customer_id"

    ROOMS = "rooms"
    ROOMS__id = "id"
    ROOMS__created_at = "created_at"
    ROOMS__user_id = "user_id"
    ROOMS__agent_id = "agent_id"
    ROOMS__agent_proactivity = "agent_proactivity"
    ROOMS__subscribe_msg_sent = "subscribe_msg_sent"
    ROOMS__disabled_by_admin = "disabled_by_admin"
    ROOMS__last_msg_sent_at = "last_msg_sent_at"

    MESSAGES = "messages"
    MESSAGES__id = "id"
    MESSAGES__sender_id = "sender_id"
    MESSAGES__room_id = "room_id"
    MESSAGES__created_at = "created_at"
    MESSAGES__content = "content"
    MESSAGES__type = "type"
    MESSAGES__sent_by_admin = "sent_by_admin"
    MESSAGES__log = "log"

    SCHEDULE = "schedule"
    SCHEDULE__id = "id"
    SCHEDULE__room_id = "room_id"
    SCHEULDE__message_id = "message_id"
    SCHEDULE__created_at = "created_at"
    SCHEDULE__run_at = "run_at"
    SCHEDULE__type = "type"  # respond, remind, revive
    SCHEDULE__info = "info"
    SCHEDULE__complete = "complete"

    def __str__(self) -> str:
        return self.value


def utc_now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def generate_uuid():
    return str(uuid.uuid4())


class Agent(BaseModel):
    id: str = Field(default_factory=generate_uuid)
    first_message: str = Field(default="Hey there!")
    telegram_chat_id: Optional[str] = Field(default=None)
    bird_channel_id: Optional[str] = Field(default=None)
    prompt: str = Field(default="You are Chris, a really cool person")
    default_proactivity: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Proactivity scale from 0 (not proactive) to 1 (very proactive)",
    )
    subscribe_enabled: bool = Field(default=True)
    free_msg_limit: Optional[int] = Field(default=15)
    subscribe_msg: Optional[str] = Field(default=None)
    subscribe_url: Optional[str] = Field(default=None)


class User(BaseModel):
    id: str = Field(description="UUID generated by Supabase Auth")
    phone_number: str
    created_at: datetime = Field(default_factory=utc_now)
    birthday: Optional[str] = Field(default=None)
    telegram_uid: Optional[str] = Field(default=None)
    customer_id: Optional[str] = Field(default=None)
    subscription_id: Optional[str] = Field(default=None)
    subscription_status: Optional[str] = Field(default=None)


class Room(BaseModel):
    id: str = Field(default_factory=generate_uuid)
    created_at: datetime = Field(default_factory=utc_now)
    user_id: str
    agent_id: str
    agent_proactivity: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Agent proactivity for a particular room (0 if a user has texted STOP)",
    )
    subscribe_msg_sent: bool = Field(default=False)
    disabled_by_admin: bool = Field(default=False)
    last_msg_sent_at: datetime = Field(
        default_factory=utc_now,
        description="Time of last message sent by either agent or user",
    )


class Message(BaseModel):
    id: str = Field(default_factory=generate_uuid)
    sender_id: str
    room_id: str
    created_at: datetime = Field(default_factory=utc_now)
    content: str = Field(default=None)
    sent_by_admin: bool = Field(default=False)
    log: Optional[Union[List[Dict[str, Any]], str]] = Field(
        default=None, description="JSONB field for agent logs"
    )

    @field_validator("log", mode="before")
    def parse_log(cls, value):
        if isinstance(value, str):
            try:
                return json.loads(value)
            except json.JSONDecodeError:
                return value  # Leave it as string if it can't be parsed
        return value


class Schedule(BaseModel):
    id: str = Field(default_factory=generate_uuid)
    room_id: str
    message_id: Optional[str]
    created_at: datetime = Field(default_factory=utc_now)
    run_at: str
    type: Literal["respond", "remind", "revive"] = Field(default="respond")
    task: Optional[str] = Field(default=None)
    complete: bool = Field(default=False)


TableModel = Union[
    User,
    Agent,
    Room,
    Message,
    Schedule,
]
TABLE_MODEL_MAP = {
    Tables.USERS: User,
    Tables.AGENTS: Agent,
    Tables.ROOMS: Room,
    Tables.MESSAGES: Message,
    Tables.SCHEDULE: Schedule,
}
