import json
import re
from typing import Dict, List, Optional, Union
from uuid import uuid4

import litellm
from litellm import (
    ModelResponse,
    RateLimitError,
    completion,
    get_supported_openai_params,
    speech,
)
from tenacity import (
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

from config.config import config, get_api_key
from mini.core.error import error_handler
from mini.core.exceptions import MessageParsingError
from mini.core.logger import get_logger
from mini.core.schema.llm import LLMProviders
from mini.storage.s3 import S3FileStore

logger = get_logger(__name__)


class LLMManager:
    """Class for Large Language Models (LLMs) usage powered by LiteLLM"""

    def __init__(self, llm_name: str, llm_provider: LLMProviders):
        self.llm_name: str = llm_name
        self.api_key: str = get_api_key(llm_provider)
        litellm.api_key = self.api_key
        litellm.modify_params = True
        self.supports_json_mode = self._check_json_mode_support()
        self.supports_vision = self._check_vision_support()

    @error_handler("LLM")
    def _check_json_mode_support(self) -> bool:
        """
        Returns true of LiteLLM provides a json response formatter for the model
        https://docs.litellm.ai/docs/completion/json_mode
        """
        supported_params = get_supported_openai_params(model=self.llm_name)
        return "response_format" in supported_params

    @retry(
        stop=stop_after_attempt(5),
        wait=wait_exponential(multiplier=1, min=4, max=10),
        retry=retry_if_exception_type((RateLimitError, Exception)),
        reraise=True,
    )
    def _attempt_completion(self, **kwargs) -> ModelResponse:
        return completion(api_key=self.api_key, **kwargs)

    @error_handler("LLM")
    def generate_response(
        self,
        messages: List[Dict[str, str]],
        system_prompt: Optional[str] = None,
        json_mode: Optional[bool] = False,
        expect_json: Optional[bool] = False,
        **kwargs,
    ) -> Union[str, Dict]:
        """
        Generate a response using the specified model.

        :param messages: List of message dictionaries with 'role' and 'content' keys
        :param system_prompt: Optional system prompt to guide the model's behavior
        :param json_mode: Optional flag to enable JSON mode output
        :param expect_json: Optional flag to indicate whether the response is expected to be in JSON format
        :param kwargs: Additional arguments to pass to the litellm completion function
        :return: The generated response as a string OR as a json loaded object if json_mode is True
        """
        prepared_messages = self._prepare_messages(messages)
        if system_prompt:
            prepared_messages = [
                {"role": "system", "content": system_prompt}
            ] + prepared_messages

        if json_mode and self.supports_json_mode:
            kwargs["response_format"] = {"type": "json_object"}

        completion_kwargs = {
            "model": self.llm_name,
            "messages": prepared_messages,
            **kwargs,
        }

        try:
            response = self._attempt_completion(**completion_kwargs)
            content = response.choices[0].message.content
            logger.info(f"🟢 Generated by LLM: {content}")

            if json_mode or expect_json:
                content = self._clean_and_parse_llm_json_output(content)

            return content

        except RateLimitError as e:
            logger.error(f"Rate limit exceeded after multiple retries: {str(e)}")
            raise

        except Exception as e:
            logger.error(
                f"An unexpected error occurred after multiple retries: {str(e)}"
            )
            raise

    def generate_and_upload_speech(self, text: str, voice: str) -> str:
        """Creates speech mp3 and uploads it to filestore. Returns uploaded URL."""
        # try:
        response = speech(
            model=self.llm_name,
            voice=voice,
            input=text,
        )
        audio_content = response.content
        fs = S3FileStore()
        key = f"{config.ENVIRONMENT}/{uuid4()}.wav"
        content_type = "audio/mpeg"

        fs.write(key, audio_content, content_type)
        presigned_url = fs.generate_presigned_url(key, content_type)
        return presigned_url, content_type
        # except Exception as e:
        #     logger.error(f"Error in generate_and_upload_speech: {str(e)}")
        #     raise

    @error_handler("LLM")
    def _prepare_messages(self, messages: List[Dict[str, str]]) -> List[Dict[str, str]]:
        """
        Prepare messages for LLM input by combining consecutive user messages.

        :param messages: List of message dictionaries with 'role' and 'content' keys
        :return: Prepared list of message dictionaries
        """
        prepared_messages = []
        for msg in messages:
            role = msg["role"]
            content = str(msg["content"])  # Ensure content is a string

            if (
                prepared_messages
                and prepared_messages[-1]["role"] == "user"
                and role == "user"
            ):
                # If the current message is from a user and the last message was also from a user,
                # append the content with a pipe symbol
                prepared_messages[-1]["content"] += f" | {content}"
            else:
                # Otherwise, add a new message entry
                prepared_messages.append({"role": role, "content": content})

        # Check if the last message is from the assistant
        if prepared_messages and prepared_messages[-1]["role"] == "assistant":
            # If so, append a user message with "[ignore]" content
            prepared_messages.append({"role": "user", "content": "[ignore]"})

        return prepared_messages

    @error_handler("LLM")
    def _clean_and_parse_llm_json_output(self, llm_output: str) -> dict:
        """
        Cleans up the output of an LLM and returns a JSON object.

        Args:
            llm_output: The raw output of an LLM.

        Returns:
            dict: A dictionary representing the cleaned and parsed JSON object.
        """
        start_index = llm_output.find("{")
        end_index = llm_output.rfind("}") + 1
        cleaned_output = llm_output[start_index:end_index].strip()
        cleaned_output = re.sub(r"\n|\r", "", cleaned_output)
        cleaned_output = re.sub(r"\s+", " ", cleaned_output)

        try:
            json_data = json.loads(cleaned_output)
        except json.JSONDecodeError as jde:
            raise MessageParsingError(
                f"Invalid JSON output from LLM. Instead got {llm_output}"
            ) from jde

        return json_data

    def describe_images(self, system_prompt: str, image_urls: List[str]) -> str:
        """
        Generate a description of images using the vision-capable model.

        :param system_prompt: System prompt to guide the model's behavior
        :param image_urls: List of image URLs to be described
        :param user_prompt: Optional user prompt to customize the image description request
        :return: The generated response as a string
        """

        if not self.supports_vision:
            raise ValueError(
                f"The model {self.llm_name} does not support vision tasks."
            )

        messages = [
            {"role": "system", "content": system_prompt},
            {
                "role": "user",
                "content": [
                    *[
                        {"type": "image_url", "image_url": {"url": url}}
                        for url in image_urls
                    ]
                ],
            },
        ]

        response = self._attempt_completion(model=self.llm_name, messages=messages)

        return response.choices[0].message.content

    @error_handler("LLM")
    def _check_vision_support(self) -> bool:
        """
        Returns true if the model supports vision inputs
        """
        return litellm.supports_vision(model=self.llm_name)
