from typing import List, Dict, Optional, Union, Dict
import litellm
from litellm import get_supported_openai_params
from zootopia.core.logger import logger
import re
import json

class LLM:
    """Class for Large Language Models (LLMs) usage powered by LiteLLM"""

    def __init__(self, llm_name: str):
        self.llm_name: str = llm_name
        litellm.modify_params = True
        self.supports_json_mode = self._check_json_mode_support()

    def _check_json_mode_support(self) -> bool:
        """
        Returns true of LiteLLM provides a json response formatter for the model
        https://docs.litellm.ai/docs/completion/json_mode
        """
        try:
            supported_params = get_supported_openai_params(model=self.llm_name)
            return "response_format" in supported_params
        except Exception as e:
            logger.warning(f"Error checking JSON mode support: {e}")
            return False

    def generate_response(
        self,
        messages: List[Dict[str, str]],
        system_prompt: Optional[str] = None,
        json_mode: Optional[bool] = False,
        **kwargs,
    ) -> Union[str, Dict]:
        """
        Generate a response using the specified model.

        :param messages: List of message dictionaries with 'role' and 'content' keys
        :param system_prompt: Optional system prompt to guide the model's behavior
        :param json_mode: Optional flag to enable JSON mode output
        :param kwargs: Additional arguments to pass to the litellm completion function
        :return: The generated response as a string OR as a json loaded object if json_mode is True
        """
        try:
            prepared_messages = self._prepare_messages(messages)
            if system_prompt:
                prepared_messages = [
                    {"role": "system", "content": system_prompt}
                ] + prepared_messages

            if json_mode and self.supports_json_mode:
                kwargs["response_format"] = {"type": "json_object"}

            response = litellm.completion(
                model=self.llm_name, messages=prepared_messages, **kwargs
            )
            content = response.choices[0].message.content
            logger.info(f"🟢 Generated by LLM: {content}")

            if json_mode:
                content = self._clean_and_parse_llm_json_output(content)

            return content
        except Exception as e:
            print(f"🔴 Error generating response: {e}")
            return ""

    def _prepare_messages(self, messages: List[Dict[str, str]]) -> List[Dict[str, str]]:
        """
        Prepare messages for LLM input by combining consecutive user messages.

        :param messages: List of message dictionaries with 'role' and 'content' keys
        :return: Prepared list of message dictionaries
        """
        prepared_messages = []
        for msg in messages:
            role = msg["role"]
            content = str(msg["content"])  # Ensure content is a string

            if (
                prepared_messages
                and prepared_messages[-1]["role"] == "user"
                and role == "user"
            ):
                # If the current message is from a user and the last message was also from a user,
                # append the content with a pipe symbol
                prepared_messages[-1]["content"] += f" | {content}"
            else:
                # Otherwise, add a new message entry
                prepared_messages.append({"role": role, "content": content})

        # Check if the last message is from the assistant
        if prepared_messages and prepared_messages[-1]["role"] == "assistant":
            # If so, append a user message with "[ignore]" content
            prepared_messages.append({"role": "user", "content": "[ignore]"})

        return prepared_messages
    
    def _clean_and_parse_llm_json_output(self, llm_output: str) -> dict:
        """
        Cleans up the output of an LLM and returns a JSON object.

        Args:
            llm_output: The raw output of an LLM.

        Returns:
            dict: A dictionary representing the cleaned and parsed JSON object.
        """
        start_index = llm_output.find("{")
        end_index = llm_output.rfind("}") + 1
        cleaned_output = llm_output[start_index:end_index].strip()
        cleaned_output = re.sub(r"\n|\r", "", cleaned_output)

        cleaned_output = re.sub(r"\s+", " ", cleaned_output)

        try:
            json_data = json.loads(cleaned_output)
        except json.JSONDecodeError:
            return {"error": f"Invalid JSON output from LLM. Instead got {llm_output}"}

        return json_data
