import json
import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field, field_validator

from mini.utils.time import utc_now


class Tables(str, Enum):
    """Tables available in the database."""

    AGENTS = "agents"
    AGENTS__id = "id"
    AGENTS__name = "name"
    AGENTS__description = "description"
    AGENTS__first_message = "first_message"
    AGENTS_example_conversation = "example_conversation"
    AGENTS__bird_channel_id = "bird_channel_id"
    AGENTS__default_proactivity = "default_proactivity"
    AGENTS__free_msg_limit = "free_msg_limit"
    AGENTS__subscribe_msg = "subscribe_msg"
    AGENTS__image_url = "image_url"

    USERS = "users"
    USERS__id = "id"
    USERS__created_at = "created_at"
    USERS__phone_number = "phone_number"
    USERS__telegram_uid = "telegram_uid"
    USERS__birthday = "birthday"
    USERS__customer_id = "customer_id"
    USERS__is_subscribed = "is_subscribed"
    USERS__litellm_cost = "litellm_cost"

    ROOMS = "rooms"
    ROOMS__id = "id"
    ROOMS__created_at = "created_at"
    ROOMS__user_id = "user_id"
    ROOMS__agent_id = "agent_id"
    ROOMS__agent_proactivity = "agent_proactivity"
    ROOMS__subscribe_msg_sent = "subscribe_msg_sent"
    ROOMS__disabled_by_admin = "disabled_by_admin"
    ROOMS__last_msg_sent_at = "last_msg_sent_at"
    ROOMS__agent_last_msg_sent_at = "agent_last_msg_sent_at"

    MESSAGES = "messages"
    MESSAGES__id = "id"
    MESSAGES__sender_id = "sender_id"
    MESSAGES__room_id = "room_id"
    MESSAGES__created_at = "created_at"
    MESSAGES__content = "content"
    MESSAGES__type = "type"
    MESSAGES__sent_by_admin = "sent_by_admin"
    MESSAGES__log = "log"

    SUBSCRIPTIONS = "subscriptions"
    SUBSCRIPTIONS__id = "id"
    SUBSCRIPTIONS__user_id = "user_id"
    SUBSCRIPTIONS__status = "status"

    SCHEDULE = "schedule"
    SCHEDULE__id = "id"
    SCHEDULE__room_id = "room_id"
    SCHEULDE__message_id = "message_id"
    SCHEDULE__created_at = "created_at"
    SCHEDULE__run_at = "run_at"
    SCHEDULE__type = "type"  # respond, remind, revive
    SCHEDULE__info = "info"
    SCHEDULE__complete = "complete"

    def __str__(self) -> str:
        return self.value


def generate_uuid():
    return str(uuid.uuid4())


class Agent(BaseModel):
    __tablename__ = Tables.AGENTS

    id: str = Field(default_factory=generate_uuid)
    name: str
    description: str
    first_message: str
    bird_channel_id: str
    prompt: str
    free_msg_limit: int
    subscribe_msg: str
    default_proactivity: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Proactivity scale from 0 (not proactive) to 1 (very proactive)",
    )
    image_url: Optional[str]


class User(BaseModel):
    __tablename__ = Tables.USERS

    id: str = Field(description="UUID generated by Supabase Auth")
    phone_number: str
    created_at: datetime = Field(default_factory=utc_now)
    birthday: Optional[str] = Field(default=None)
    telegram_uid: Optional[str] = Field(default=None)
    customer_id: Optional[str] = Field(default=None)
    is_subscribed: bool = Field(default=False)
    litellm_cost: float = Field(default=0.0)


class Room(BaseModel):
    __tablename__ = Tables.ROOMS

    id: str = Field(default_factory=generate_uuid)
    created_at: datetime = Field(default_factory=utc_now)
    user_id: str
    agent_id: str
    subscribe_msg_sent: bool = Field(default=False)
    agent_proactivity: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Agent proactivity for a particular room (0 if a user has texted STOP)",
    )
    disabled_by_admin: bool = Field(default=False)
    last_msg_sent_at: datetime = Field(
        default_factory=utc_now,
        description="Time of last message sent by either agent or user",
    )
    agent_last_msg_sent_at: datetime = Field(
        default_factory=utc_now,
        description="Time of last message sent by agent",
    )


class Message(BaseModel):
    __tablename__ = Tables.MESSAGES

    id: str = Field(default_factory=generate_uuid)
    sender_id: str
    room_id: str
    created_at: datetime = Field(default_factory=utc_now)
    content: str = Field(default=None)
    sent_by_admin: bool = Field(default=False)
    log: Optional[Union[List[Dict[str, Any]], str]] = Field(
        default=None, description="JSONB field for agent logs"
    )

    @field_validator("log", mode="before")
    def parse_log(cls, value):
        if isinstance(value, str):
            try:
                return json.loads(value)
            except json.JSONDecodeError:
                return value  # Leave it as string if it can't be parsed
        return value


class Subscription(BaseModel):
    __tablename__ = Tables.SUBSCRIPTIONS

    id: str
    user_id: str
    status: str


class Schedule(BaseModel):
    id: str = Field(default_factory=generate_uuid)
    room_id: str
    message_id: Optional[str]
    created_at: datetime = Field(default_factory=utc_now)
    run_at: str
    type: Literal["respond", "remind", "revive"] = Field(default="respond")
    task: Optional[str] = Field(default=None)
    complete: bool = Field(default=False)


TableModel = Union[User, Agent, Room, Message, Schedule, Subscription]
TABLE_MODEL_MAP = {
    Tables.USERS: User,
    Tables.AGENTS: Agent,
    Tables.ROOMS: Room,
    Tables.MESSAGES: Message,
    Tables.SCHEDULE: Schedule,
    Tables.SUBSCRIPTIONS: Subscription,
}
